# Spring Boot 配置

# 服务器端口
server.port=8080

# 主类配置
spring.main.main-class=com.lbc_plot.MainApplication

# 数据库配置
spring.datasource.url=jdbc:sqlite:./data/project.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# JPA配置
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# 日志配置
logging.level.com.lbc_plot=INFO
logging.level.org.springframework=WARN
logging.level.org.hibernate=ERROR
